name: MeshCore Proxy
version: "0.1.0"
slug: meshcore_proxy
description: Run meshcore-proxy inside Home Assistant OS
url: "https://github.com/mival/hass-meshcore-proxy"
init: false
arch:
  - aarch64
  - amd64
  - armv7
  - i386
startup: services
boot: auto
host_network: true
options:
  meshcore_proxy_args: ""
schema:
  meshcore_proxy_args: str?